version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongo-db
    environment:
      - NODE_ENV=development  # Set the Node.js environment to development
    links:
      - mongo-db

  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data to a volume

volumes:
  mongo-data:
